### ISSUE TITLE
Error compiling with Msys

### ISSUE THREAD

**Issue by Revertron** [mxre/winres#4]
Hi, I am trying to use GNU compiler on windows and utilities from Msys.
But I'm having this error when I'm trying to build:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', C:\bot\slave\stable-dist-rustc-win-gnu-64\build\src\libcore\option.rs:323
```
Why is it printing the path I haven't in the first place? I don't have `C:\bot\slave\...` :(

**Comment by mxre** [comment]
The path is from the rust core library you installed (thus the path is local to the build bot that provided it).

The error message is normal for any call to Option::unwrap() where the contained value is None.
I suggest setting `RUST_BACKTRACE=1` to get a stacktrace, because without a trace this bug report is incomplete.
